spring.application.name=sales_service

spring.datasource.url=jdbc:postgresql://localhost:5432/electro-store
spring.datasource.username=postgres
spring.datasource.password=super
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.port=8081

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.sql.init.platform=postgres

spring.jpa.properties.hibernate.default_schema=public

logging.level.org.hibernate.boot=DEBUG
logging.level.org.hibernate.boot.model.internal=TRACE
logging.level.org.hibernate.orm.mapping=DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

management.influx.metrics.export.bucket=nais_bucket
management.influx.metrics.export.auto-create-bucket=false

influx.bucket=nais_bucket
influx.org=nais_org

spring.neo4j.uri=bolt://neo4j:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=password