version: '3.9'

services:
  products_maintenance:
    build: ./products_maintenance
    container_name: products_maintenance
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra
      - SALES_BASE_URL=http://sales_service:8081
    networks:
      - electric-store-net

  cassandra:
    image: cassandra:4.1
    container_name: pm_cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_KEYSPACE: product_portfolio
      CASSANDRA_CLUSTER_NAME: ProductCluster
    command: cassandra -f
    networks:
      - electric-store-net

  sales_service:
    build: ./sales_service
    container_name: sales_service
    ports:
      - "8081:8081"
    depends_on:
      - postgreSQL
      - influxdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgreSql:5432/electro-store
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=super
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=my-super-secret-auth-token
      - INFLUX_ORG=nais_org
      - INFLUX_BUCKET=nais_bucket
    networks:
      - electric-store-net

  postgreSQL:
    image: postgres:15
    container_name: postgreSql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_DB: electro-store
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - electric-store-net

  influxdb:
    image: influxdb:2.7.6
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=nais
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=nais_org
      - DOCKER_INFLUXDB_INIT_BUCKET=nais_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    networks:
      - electric-store-net
volumes:
  postgres_data:
  influxdb-storage:

networks:
  electric-store-net:
    driver: bridge