version: '3.9'

services:
  nats:
    image: nats:latest
    command: ["-js", "-p", "4222", "-m", "8222"]
    ports: ["4222:4222", "8222:8222"]
    restart: unless-stopped
    networks: [electric-store-net]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_DB: electro-store
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [electric-store-net]

  cassandra:
    image: cassandra:4.1
    ports: ["9042:9042"]
    environment:
      CASSANDRA_KEYSPACE: product_portfolio
      CASSANDRA_CLUSTER_NAME: ProductCluster
    command: cassandra -f
    networks: [electric-store-net]

  influxdb:
    image: influxdb:2.7.6
    ports: ["8086:8086"]
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=nais
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=nais_org
      - DOCKER_INFLUXDB_INIT_BUCKET=nais_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [electric-store-net]

  products_maintenance:
    build: ./products_maintenance
    ports: ["8080:8080"]
    depends_on: [cassandra, nats]
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra
      - NATS_URL=nats://nats:4222
    networks: [electric-store-net]

  sales_service:
    build: ./sales_service
    ports: ["8081:8081"]
    depends_on: [postgres, influxdb, nats]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/electro-store
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=super
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=my-super-secret-auth-token
      - INFLUX_ORG=nais_org
      - INFLUX_BUCKET=nais_bucket
      - NATS_URL=nats://nats:4222
    networks: [electric-store-net]

volumes:
  postgres_data:
  influxdb-storage:

networks:
  electric-store-net:
    driver: bridge
